apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: affinitynginx
  name: affinitynginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: agentpool
              operator: In
              values:
              - goldenpool
  containers:
  - image: nginx
    name: affinitynginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
