apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: highcpu
  name: highcpu
spec:
  containers:
  - image: nginx
    name: highcpu
    resources:
      requests:
        cpu: "4000m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: agentpool
            operator: In
            values:
            - goldpool
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
